version: "3.9"

services:
  chickenfarm-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_FILE: src/ChickenFarm.Api/ChickenFarm.Api.csproj 
        PROJECT_DLL: ChickenFarm.Api.dll
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PATH_BASE=/chickenfarm-api

  chickenfarm-reporting-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_FILE: src/ChickenFarm.Reporting.Api/ChickenFarm.Reporting.Api.csproj
        PROJECT_DLL: ChickenFarm.Reporting.Api.dll
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:81
      - PATH_BASE=/chickenfarm-reporting-api
      
  chickenfarm-tasks-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_FILE: src/ChickenFarm.Tasks.Api/ChickenFarm.Tasks.Api.csproj
        PROJECT_DLL: ChickenFarm.Tasks.Api.dll
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:82
      - PATH_BASE=/chickenfarm-tasks-api
   
  chickenfarm-logging:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
    
  chickenfarm-rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "5672:5672"
      - "15672:15672"

  chickenfarm-zipkin:
    ports:
      - "5411:9411"