apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  topic: tasks
  route: /NewTaskPublished
  pubsubname: pubsub
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://root:root@chickenfarm-rabbitmq:5672"
