apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://chickenfarm-zipkin:9411/api/v2/spans"